# Execute this workflow when you push
on: [push]

jobs:
  # job name(Any job name)
  magic_pod_job:

    # Specify virtual machine format
    runs-on: macos-latest  # Specify mac this time

    # Steps in the job
    steps:
      # Step1(Checkout)
      - name: Checkout
        uses: actions/checkout@v3 # Specify the latest version of actions
    # Step2(Execute batch tests using MagicPod)
      - name: Batch run test
        env:
          MAGICPOD_API_TOKEN: ${{ secrets.MAGICPOD_API_TOKEN }}  # Variable name set in GitHub
        run: bash run_magicpod_test.sh  # Shell script created earlier
